eureka:
  client:
    service-url:  # 服务注册中心的地址
      defaultZone: http://euk1.com:7001/eureka/   #单节点搭建
#    fetch-registry: false
#    register-with-eureka: false
  instance:
    hostname: euk1.com
    metadata-map:
      dalao: csc
server:
  port: 7001
